In [ ]:
import random
import numpy as np
import pandas as pd

In [ ]:
# import data
dataset = pd.read_csv('https://raw.githubusercontent.com/nissasyfsgt/DATASET/main/data.csv', encoding='latin-1')
dataset.head(15)

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0
5,USER Ya bani taplak dkk \xf0\x9f\x98\x84\xf0\x...,1,1,0,1,0,0,0,0,1,0,1,0
6,deklarasi pilkada 2018 aman dan anti hoax warg...,0,0,0,0,0,0,0,0,0,0,0,0
7,Gue baru aja kelar re-watch Aldnoah Zero!!! pa...,0,1,0,0,0,0,0,0,0,0,0,0
8,Nah admin belanja satu lagi port terbaik nak m...,0,0,0,0,0,0,0,0,0,0,0,0
9,USER Enak lg klo smbil ngewe',0,1,0,0,0,0,0,0,0,0,0,0
10,"Setidaknya gw punya jari tengah buat lu, sebel...",1,1,1,0,0,0,0,0,1,1,0,0
11,USER USER USER USER BANCI KALENG MALU GA BISA ...,1,1,1,0,0,0,0,1,0,1,0,0
12,Kalo belajar ekonomi mestinya jago memprivatis...,0,0,0,0,0,0,0,0,0,0,0,0
13,Aktor huruhara 98 Prabowo S ingin lengserkan p...,1,0,1,0,0,0,0,0,1,1,0,0
14,USER Bu guru enakan jadi jablay atau guru esde...,1,1,1,0,0,0,0,1,0,1,0,0

In [ ]:
dataset.drop(['HS', 'HS_Individual',	'HS_Group',	'HS_Religion',	'HS_Race',	'HS_Physical',	'HS_Gender',	'HS_Other',	'HS_Weak',	'HS_Moderate',	'HS_Strong'], axis=1, inplace=True)

In [ ]:
dataset.head(21)

                                                Tweet  Abusive
0   - disaat semua cowok berusaha melacak perhatia...        1
1   RT USER: USER siapa yang telat ngasih tau elu?...        1
2   41. Kadang aku berfikir, kenapa aku tetap perc...        0
3   USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...        0
4   USER USER Kaum cebong kapir udah keliatan dong...        1
5   USER Ya bani taplak dkk \xf0\x9f\x98\x84\xf0\x...        1
6   deklarasi pilkada 2018 aman dan anti hoax warg...        0
7   Gue baru aja kelar re-watch Aldnoah Zero!!! pa...        1
8   Nah admin belanja satu lagi port terbaik nak m...        0
9                       USER Enak lg klo smbil ngewe'        1
10  Setidaknya gw punya jari tengah buat lu, sebel...        1
11  USER USER USER USER BANCI KALENG MALU GA BISA ...        1
12  Kalo belajar ekonomi mestinya jago memprivatis...        0
13  Aktor huruhara 98 Prabowo S ingin lengserkan p...        0
14  USER Bu guru enakan jadi jablay atau guru esde...        1
15  USER USER USER USER USER USER Lawan bicara gw ...        1
16        Belakangan ini kok fikiran ampas banget ya'        0
17  Ari sarua beki mah repeh monyet\xf0\x9f\x98\x8...        1
18  Jadi cowo itu harus Gantle kalo ga Gantle itu ...        1
19                USER Slga mnr bom \xf0\x9f\x98\x82'        0
20  Asw ya tapi gua jarang ngambek, tacut wkkwkwkw...        1

In [ ]:
dataset.rename(columns={'Abusive':'Sentiment'}, inplace=True)

In [ ]:
dataset

                                                   Tweet  Sentiment
0      - disaat semua cowok berusaha melacak perhatia...          1
1      RT USER: USER siapa yang telat ngasih tau elu?...          1
2      41. Kadang aku berfikir, kenapa aku tetap perc...          0
3      USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...          0
4      USER USER Kaum cebong kapir udah keliatan dong...          1
...                                                  ...        ...
13164  USER jangan asal ngomong ndasmu. congor lu yg ...          1
13165                       USER Kasur mana enak kunyuk'          1
13166  USER Hati hati bisu :( .g\n\nlagi bosan huft \...          0
13167  USER USER USER USER Bom yang real mudah terdet...          0
13168  USER Mana situ ngasih(": itu cuma foto ya kuti...          1

[13169 rows x 2 columns]

In [ ]:
dataset['Sentiment'] = dataset['Sentiment'].map({0: 'Positive', 1: 'Negative'})

In [ ]:
dataset

                                                   Tweet Sentiment
0      - disaat semua cowok berusaha melacak perhatia...  Negative
1      RT USER: USER siapa yang telat ngasih tau elu?...  Negative
2      41. Kadang aku berfikir, kenapa aku tetap perc...  Positive
3      USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...  Positive
4      USER USER Kaum cebong kapir udah keliatan dong...  Negative
...                                                  ...       ...
13164  USER jangan asal ngomong ndasmu. congor lu yg ...  Negative
13165                       USER Kasur mana enak kunyuk'  Negative
13166  USER Hati hati bisu :( .g\n\nlagi bosan huft \...  Positive
13167  USER USER USER USER Bom yang real mudah terdet...  Positive
13168  USER Mana situ ngasih(": itu cuma foto ya kuti...  Negative

[13169 rows x 2 columns]

In [ ]:
dataset.to_csv (r'dataset_baru.csv', index = False, header=True)

print (dataset)

                                                   Tweet Sentiment
0      - disaat semua cowok berusaha melacak perhatia...  Negative
1      RT USER: USER siapa yang telat ngasih tau elu?...  Negative
2      41. Kadang aku berfikir, kenapa aku tetap perc...  Positive
3      USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...  Positive
4      USER USER Kaum cebong kapir udah keliatan dong...  Negative
...                                                  ...       ...
13164  USER jangan asal ngomong ndasmu. congor lu yg ...  Negative
13165                       USER Kasur mana enak kunyuk'  Negative
13166  USER Hati hati bisu :( .g\n\nlagi bosan huft \...  Positive
13167  USER USER USER USER Bom yang real mudah terdet...  Positive
13168  USER Mana situ ngasih(": itu cuma foto ya kuti...  Negative

[13169 rows x 2 columns]

In [ ]:
dataset.head(20)

                                                Tweet Sentiment
0   - disaat semua cowok berusaha melacak perhatia...  Negative
1   RT USER: USER siapa yang telat ngasih tau elu?...  Negative
2   41. Kadang aku berfikir, kenapa aku tetap perc...  Positive
3   USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...  Positive
4   USER USER Kaum cebong kapir udah keliatan dong...  Negative
5   USER Ya bani taplak dkk \xf0\x9f\x98\x84\xf0\x...  Negative
6   deklarasi pilkada 2018 aman dan anti hoax warg...  Positive
7   Gue baru aja kelar re-watch Aldnoah Zero!!! pa...  Negative
8   Nah admin belanja satu lagi port terbaik nak m...  Positive
9                       USER Enak lg klo smbil ngewe'  Negative
10  Setidaknya gw punya jari tengah buat lu, sebel...  Negative
11  USER USER USER USER BANCI KALENG MALU GA BISA ...  Negative
12  Kalo belajar ekonomi mestinya jago memprivatis...  Positive
13  Aktor huruhara 98 Prabowo S ingin lengserkan p...  Positive
14  USER Bu guru enakan jadi jablay atau guru esde...  Negative
15  USER USER USER USER USER USER Lawan bicara gw ...  Negative
16        Belakangan ini kok fikiran ampas banget ya'  Positive
17  Ari sarua beki mah repeh monyet\xf0\x9f\x98\x8...  Negative
18  Jadi cowo itu harus Gantle kalo ga Gantle itu ...  Negative
19                USER Slga mnr bom \xf0\x9f\x98\x82'  Positive

In [ ]:
#here we created a dependent and independent variables
X = dataset[['Tweet','Sentiment']]
y = dataset[[]]

In [ ]:
# Spliting data into train data and test data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) #20% test, 80% training

In [ ]:
# Printing the size of X training dataset
X_train.shape

(10535, 2)

In [ ]:
X_test.shape

(2634, 2)

In [ ]:
# Printing the size of Y training dataset
y_train.shape

(10535, 0)

In [ ]:
# Printing the size of Y testing dataset
y_test.shape

(2634, 0)

In [ ]:
X_train.to_csv (r'dataset_train.csv', index = False, header=True)

In [ ]:
X_test.to_csv (r'dataset_test.csv', index = False, header=True)

In [ ]:
datasettrain = pd.read_csv('/content/dataset_train.csv', encoding='latin-1')
datasettrain

                                                   Tweet Sentiment
0      \xf0\x9f\x93\x8c Himmler merupakan pimpinan de...  Positive
1                                    USER Iya anjir dah'  Negative
2      USER Adatuh temen sekelas di sma, dia cakep im...  Positive
3      USER USER USER USER Mongomong soal ospek, jadi...  Positive
4                                   Bajingan punya line'  Negative
...                                                  ...       ...
10530  ~; Yg jelas, klw ada foto2 yg begitu:; #lombaT...  Positive
10531  rp haneul sok pemes padahal cupu mau aja dient...  Negative
10532  A orangnya enak diajak curhat, setia dan romantis  Positive
10533  #Kertayu; #Muba; #Sedekah_Bumi; #Lempar_Lemang...  Positive
10534  Bodohnya cerita TAK ADA CINTA SEPERTIMU ni. To...  Negative

[10535 rows x 2 columns]

In [ ]:
datasettest = pd.read_csv('/content/dataset_test.csv', encoding='latin-1')
datasettest

                                                  Tweet Sentiment
0     Usir Dubes Myanmar dr Negri ini. Ksh peringata...  Positive
1     USER Ancaman bom dari mata sipit, juga lucu2an...  Negative
2     Pria Belanda Ini Jadi Mualaf Usai Ikuti Perjal...  Positive
3                                   USER Jancuk jancuk'  Negative
4     USER Eh nurull kuliah dimana? Jurusan apa? Ha ...  Positive
...                                                 ...       ...
2629                       Ngocok memek enak kali ya..'  Negative
2630  Itik yang bertelor, ayam yang mengerami.; ; Ah...  Negative
2631  USER USER mafia wasit mah milanisti aseng... J...  Positive
2632  Ini lho mengkritik yg dimaui pak USER yaitu kr...  Positive
2633  Wes ngalahi nggo tank jebule fighter assasin e...  Negative

[2634 rows x 2 columns]

In [ ]:
import tensorflow as tf

In [ ]:
train_path = pd.read_csv("/content/dataset_train.csv", encoding='latin-1') # ganti dengan directoy dari gcp bucket
alay_path = pd.read_csv("/content/new_kamusalay.csv", encoding='latin-1', header=None) # ganti dengan directoy dari gcp bucket

In [ ]:
alay_dict = alay_path.rename(columns={0: 'original', 
                                      1: 'replacement'})

In [ ]:
import re
def lowercase(text):
    return text.lower()

def remove_unnecessary_char(text):
    text = re.sub('\n',' ',text)    # Remove every '\n'
    text = re.sub('rt',' ',text)    # Remove every retweet symbol
    text = re.sub('user',' ',text)  # Remove every username
    text = re.sub('((www\.[^\s]+)|(https?://[^\s]+)|(http?://[^\s]+))',' ',text) # Remove every URL
    text = re.sub('  +', ' ', text) # Remove extra spaces
    return text

In [ ]:
def remove_nonaplhanumeric(text):
    text = re.sub('[^0-9a-zA-Z]+', ' ', text) 
    return text

In [ ]:
alay_dict_map = dict(zip(alay_dict['original'], alay_dict['replacement']))
def normalize_alay(text):
    return ' '.join([alay_dict_map[word] if word in alay_dict_map else word for word in text.split(' ')])

In [ ]:
def preprocess(text):
    text = lowercase(text) # 1
    text = remove_nonaplhanumeric(text) # 2
    text = remove_unnecessary_char(text) # 2
    text = normalize_alay(text) # 3
    return text

In [ ]:
train_path['Tweet'] = train_path['Tweet'].apply(preprocess)

decode_map = {0: "Positive", 1: "Negative"}
def decode_sentiment(label):
    return decode_map[int(label)]

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
SEQUENCE_LENGTH=300
tokenizer = Tokenizer(num_words=2000)
tokenizer.fit_on_texts(train_path.Tweet)
import json

In [ ]:
def comment_to_instances(text):
    # Tokenize text
    x_test = pad_sequences(tokenizer.texts_to_sequences([text]), maxlen=SEQUENCE_LENGTH)
    json_string = json.dumps(x_test[0].tolist())
    return json.loads(json_string)

In [ ]:
import googleapiclient.discovery
from google.api_core.client_options import ClientOptions
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "../capstone-b21-cap0156-4fa21fe5e78d.json" # change for your GCP key